# Generated by Django 4.2.3 on 2023-07-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maldetect_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
